# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Update pip and Install any needed packages specified in requirements.txt
RUN python -m pip install --upgrade pip &&\
	pip install --no-cache-dir -r requirements.txt &&\
	apt-get update &&\ 
	apt-get install -y iputils-ping

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=app.py

# Run app.py when the container launches
CMD ["python", "app.py"]

