name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ../../Dockerfile_app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/expense-tracker:latest

      - name: Create PostgreSQL Container
        run: |
          docker run --name expensedb -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -e POSTGRES_DB=expensedb -d postgres:latest

      - name: Deploy Application to Server
        run: |
          ssh root@16.171.255.74 "docker pull ${{ secrets.DOCKER_USERNAME }}/expense-tracker:latest"
          ssh root@16.171.255.74 "docker run -d --name expense-tracker ${{ secrets.DOCKER_USERNAME }}/expense-tracker:latest"
