name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t adanilkumar/expense-tracker:latest .
        docker push adanilkumar/expense-tracker:latest

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl set image deployment/expense-tracker-deployment expense-tracker=adanilkumar/expense-tracker:latest

=======
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t expense-tracker ../../Dockerfile_app

      - name: Create PostgreSQL Container
        run: |
          docker run --name expensedb -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" -e POSTGRES_DB=expensedb -d postgres:latest
>>>>>>> e804e05 (Universal App deployment)
