name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile_app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/expense-tracker:latest

      - name: Create PostgreSQL Container
        run: |
          docker run --name expensedb -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -e POSTGRES_DB=expensedb -d postgres:latest

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH Host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa 16.171.255.74 >> ~/.ssh/known_hosts

      - name: Power off existing app and redeploy Application to Server
        run: |
          ssh ubuntu@16.171.255.74 << EOF
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/expense-tracker:latest
            sudo docker stop expense-tracker || true
            sudo docker rm expense-tracker || true
            sudo docker run -d --name expense-tracker \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -p 5000:5000 \
              ${{ secrets.DOCKER_USERNAME }}/expense-tracker:latest
          EOF

      - name: Check Application Health
        run: |
          for i in {1..10}; do
            response=$(curl -s -o /dev/null -w "%{http_code}" http://16.171.255.74:5000)
            if [ $response = "200" ]; then
              echo "Application is up and running!"
              exit 0
            fi
            echo "Waiting for application to start... (Attempt $i/10)"
            sleep 5
          done
          echo "Application failed to start within the expected time."
          exit 1

      - name: Fetch Application Logs on Failure
        if: failure()
        run: |
          ssh ubuntu@16.171.255.74 "sudo docker logs expense-tracker"